{% set name = "stomp.py" %}
{% set version = "4.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 80b33ad59d14ff34503fee2472f279723cf5286399f45ea1684d137d585b0470

build:
  number: 0
  entry_points:
    - stomp = stomp.__main__:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - docopt >=0.6.2
    - python

test:
  imports:
    - stomp
    - stomp.adapter
  commands:
    - stomp --help

about:
  home: https://github.com/jasonrbriggs/stomp.py
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python STOMP client, supporting versions 1.0, 1.1 and 1.2 of the protocol
  description: |
    "stomp.py" is a Python client library for accessing messaging servers
    (such as ActiveMQ, Apollo or RabbitMQ) using the STOMP protocol
    (STOMP v1.0, STOMP v1.1 and STOMP v1.2).
    It can also be run as a standalone, command-line client for testing.
  doc_url: https://jasonrbriggs.github.io/stomp.py/index.html
  dev_url: https://github.com/jasonrbriggs/stomp.py

extra:
  recipe-maintainers:
    - anthchirp
